/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stdsystem;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author RisHaris
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/StudentRegistrationSystem/Main/ico.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonShut = new javax.swing.JButton();
        jButtonLoginADMIN = new javax.swing.JButton();
        jButtonLoginSTD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentRegistrationSystem");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schoolhouse-icon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/School-Icon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 470, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown-filled.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/main/MainMenu.png"))); // NOI18N
        jLabel1.setText("jLabel2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jButtonShut.setText("jButton1");
        jButtonShut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonShutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonShutMouseExited(evt);
            }
        });
        jButtonShut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShut, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 120, 120));

        jButtonLoginADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginADMINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginADMINMouseExited(evt);
            }
        });
        jButtonLoginADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginADMINActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 320, 210));

        jButtonLoginSTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginSTDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginSTDMouseExited(evt);
            }
        });
        jButtonLoginSTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginSTDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginSTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 320, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginADMINActionPerformed
           LoginForm sc = new LoginForm();
           sc.setVisible(true);  
           sc.pack();
           sc.setLocationRelativeTo(null);
           sc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           dispose();
    }//GEN-LAST:event_jButtonLoginADMINActionPerformed

    private void jButtonLoginSTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginSTDActionPerformed
          showScoresForm st = new showScoresForm();
           st.setVisible(true);  
           st.pack();
           st.setLocationRelativeTo(null);
          st.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          dispose();
    }//GEN-LAST:event_jButtonLoginSTDActionPerformed

    private void jButtonLoginADMINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginADMINMouseEntered
  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/Main/MainADMIN.png")));
    }//GEN-LAST:event_jButtonLoginADMINMouseEntered

    private void jButtonLoginADMINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginADMINMouseExited
  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/Main/MainMenu.png")));
    }//GEN-LAST:event_jButtonLoginADMINMouseExited

    private void jButtonLoginSTDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSTDMouseEntered
  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/Main/MainSTUDENT.png")));
    }//GEN-LAST:event_jButtonLoginSTDMouseEntered

    private void jButtonLoginSTDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSTDMouseExited
  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/Main/MainMenu.png")));
    }//GEN-LAST:event_jButtonLoginSTDMouseExited

    private void jButtonShutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShutMouseEntered
 jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown-icon-11.png")));
    }//GEN-LAST:event_jButtonShutMouseEntered

    private void jButtonShutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShutMouseExited
 jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown-filled.png")));
    }//GEN-LAST:event_jButtonShutMouseExited

    private void jButtonShutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShutActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginADMIN;
    private javax.swing.JButton jButtonLoginSTD;
    private javax.swing.JButton jButtonShut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
