/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stdsystem;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author RisHaris
 */
public class MainFormLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainFormLogin
     */
    public MainFormLogin() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/StudentRegistrationSystem/Main/ico.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonADDCourse = new javax.swing.JButton();
        jButtonADDScoreShow = new javax.swing.JButton();
        jButtonADDScore = new javax.swing.JButton();
        jButtonADDStudent1 = new javax.swing.JButton();
        jButtonMNScore = new javax.swing.JButton();
        jButtonMNStudent = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_StdCount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_CrsCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonMNCourse = new javax.swing.JButton();
        jLabel_logout = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Student Registration System");
        setMinimumSize(new java.awt.Dimension(900, 640));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonADDCourse.setBackground(new java.awt.Color(204, 204, 204));
        jButtonADDCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonADDCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courses.png"))); // NOI18N
        jButtonADDCourse.setText("Add Course");
        jButtonADDCourse.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonADDCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDCourseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonADDCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 180, 60));

        jButtonADDScoreShow.setBackground(new java.awt.Color(204, 204, 204));
        jButtonADDScoreShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonADDScoreShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow_Up_Circle.png"))); // NOI18N
        jButtonADDScoreShow.setText("Show Score");
        jButtonADDScoreShow.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonADDScoreShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDScoreShowActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonADDScoreShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 180, 60));

        jButtonADDScore.setBackground(new java.awt.Color(204, 204, 204));
        jButtonADDScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonADDScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/results.png"))); // NOI18N
        jButtonADDScore.setText("Add Score");
        jButtonADDScore.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonADDScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDScoreActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonADDScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 180, 60));

        jButtonADDStudent1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonADDStudent1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonADDStudent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/main/man.png"))); // NOI18N
        jButtonADDStudent1.setText("Add Student");
        jButtonADDStudent1.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonADDStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDStudent1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonADDStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 60));

        jButtonMNScore.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMNScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMNScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/line_add.png"))); // NOI18N
        jButtonMNScore.setText("Edit / Delete Score");
        jButtonMNScore.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonMNScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMNScoreActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMNScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 250, 60));

        jButtonMNStudent.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMNStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMNStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student-group.png"))); // NOI18N
        jButtonMNStudent.setText("Manage Student");
        jButtonMNStudent.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonMNStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMNStudentActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMNStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 220, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schoolhouse-icon.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, 130));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_StdCount.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel_StdCount.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_StdCount.setText("Student Count =");
        jPanel2.add(jLabel_StdCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 280, 120));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_CrsCount.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel_CrsCount.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_CrsCount.setText("Course Count =");
        jPanel1.add(jLabel_CrsCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 270, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UmbrellaSchoolIconBLUE.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 470, 300));

        jButtonMNCourse.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMNCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMNCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-edit.png"))); // NOI18N
        jButtonMNCourse.setText("Manage Course");
        jButtonMNCourse.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonMNCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMNCourseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonMNCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 220, 60));

        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/login/logout.png"))); // NOI18N
        jPanel3.add(jLabel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 20, 30, 60));

        jLabel_Username.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel_Username.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_Username.setText("Welcome <#####>");
        jPanel3.add(jLabel_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 110, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/login/school (2).png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/login/logout.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logout");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/main/Mainlogin.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jButton_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseExited(evt);
            }
        });
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 10, 120, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDStudent1ActionPerformed
                    AddStudentForm AddSf = new AddStudentForm();
                    AddSf.setVisible(true);
                    AddSf.pack();
                    AddSf.setLocationRelativeTo(null);
                    AddSf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
    }//GEN-LAST:event_jButtonADDStudent1ActionPerformed

    private void jButtonADDCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDCourseActionPerformed
         addCourseForm Addcf = new addCourseForm();
                    Addcf.setVisible(true);
                    Addcf.pack();
                    Addcf.setLocationRelativeTo(null);
                    Addcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  
    }//GEN-LAST:event_jButtonADDCourseActionPerformed

    private void jButton_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseEntered
jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/login/logout2.png")));
    }//GEN-LAST:event_jButton_logoutMouseEntered

    private void jButton_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseExited
jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistrationSystem/login/logout.png")));
    }//GEN-LAST:event_jButton_logoutMouseExited

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
             LoginForm sc = new LoginForm();
           sc.setVisible(true);  
           dispose();
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButtonMNStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMNStudentActionPerformed
        manageStudentsForm mngSf = new manageStudentsForm();
                    mngSf.setVisible(true);
                    mngSf.pack();
                    mngSf.setLocationRelativeTo(null);
                    mngSf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      
    }//GEN-LAST:event_jButtonMNStudentActionPerformed

    private void jButtonMNCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMNCourseActionPerformed
        manageCourseForm Mngcf = new manageCourseForm();
                    Mngcf.setVisible(true);
                    Mngcf.pack();
                    Mngcf.setLocationRelativeTo(null);
                    Mngcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonMNCourseActionPerformed

    private void jButtonADDScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDScoreActionPerformed
        addScoreForm AddSF = new addScoreForm();
                    AddSF.setVisible(true);
                    AddSF.pack();
                    AddSF.setLocationRelativeTo(null);
                    AddSF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonADDScoreActionPerformed

    private void jButtonMNScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMNScoreActionPerformed
        editDeleteScore eddS = new editDeleteScore();
                    eddS.setVisible(true);
                    eddS.pack();
                    eddS.setLocationRelativeTo(null);
                    eddS.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonMNScoreActionPerformed

    private void jButtonADDScoreShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDScoreShowActionPerformed
        showScoresForm ShowSF = new showScoresForm();
                    ShowSF.setVisible(true);
                    ShowSF.pack();
                    ShowSF.setLocationRelativeTo(null);
                    ShowSF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonADDScoreShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDCourse;
    private javax.swing.JButton jButtonADDScore;
    private javax.swing.JButton jButtonADDScoreShow;
    private javax.swing.JButton jButtonADDStudent1;
    private javax.swing.JButton jButtonMNCourse;
    private javax.swing.JButton jButtonMNScore;
    private javax.swing.JButton jButtonMNStudent;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel_CrsCount;
    public static javax.swing.JLabel jLabel_StdCount;
    public static javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
